image: ruby:latest

stages:
    - build
    - staging
    - production

build:
    stage: build
    image: node:12
    script:
    - npm ci
    - npm run build
    artifacts:
        paths:
        - .next
        - build


staging:
    type: deploy
    stage: staging
    before_script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
    only:
        - master

production:
    type: deploy
    stage: production
    before_script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
    only:
        - production
